"""
pipeline/ingest.py
==================
Load EIS .ism files acquired with Zahner software and extract their data and metadata.

Most important functions
-------------------------
load_ism(path)           -> Load a single .ism file and return an IsmRecord with freq, Z_re, Z_im and metadata.
scan_condition_dir(dir)  -> list of IsmRecord for an entire condition folder
duration_str(start, end) -> elapsed time string HH:MM:SS

Physical units
--------------
freq  : Hz
Z_re  : Ohm  (real part of impedance)
Z_im  : Ohm  (imaginary part of impedance, positive in the capacitive region)
datetime: Python datetime, timezone-aware if present in the ISM file

Python libraries and EIS convention use Z = Z_re - j*Z_im,
where Z_im is positive in the capacitive region. 
Zahner returns Z_im with negative sign -> sign is flipped in load_ism().

"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from zahner_analysis.file_import.ism_import import IsmImport


# ---------------------------------------------------------------------------
# Data class
# ---------------------------------------------------------------------------

@dataclass
class IsmRecord:
    """
    Holds all data for a single .ism file.

    Attributes
    ----------
    path       : absolute Path to the file
    freq       : frequency array [Hz], descending order as output by Zahner
    Z_re       : real part of impedance [Ohm]
    Z_im       : imaginary part [Ohm], positive in the capacitive region
    t_start    : measurement start datetime
    t_end      : measurement end datetime
    duration   : elapsed time string HH:MM:SS
    system     : instrument identifier string (e.g. 'Zennium Pro')
    T_ism_str  : internal ISM temperature string — CORRUPTED (~-0.2 C), do NOT use for temperature assignment; this field is stored for documentation only
    n_points   : number of frequency points

    Fields populated by Stage 1 (furnace log matching)
    ---------------------------------------------------
    T_nominal  : nominal temperature [C], rounded to nearest multiple of 25
    T_mean     : mean furnace temperature during measurement [C]
    T_std      : std of furnace temperature during measurement [C]
    pO2_mean   : mean pO2 during each ism measurement [bar], computed as (max+min)/2
    replica    : replica index within the (T_nominal) group, 1-based
    status     : VALID | UNSTABLE | OUTSIDE_RANGE | OUT_OF_RANGE
    """
    path:      Path
    freq:      np.ndarray
    Z_re:      np.ndarray
    Z_im:      np.ndarray
    t_start:   Optional[datetime] = None
    t_end:     Optional[datetime] = None
    duration:  str = ""
    system:    str = ""
    T_ism_str: str = ""    # corrupted field — stored for documentation only
    n_points:  int = 0

    # Populated by Stage 1
    T_nominal:  Optional[float] = None
    T_mean:     Optional[float] = None
    T_std:      Optional[float] = None
    pO2_mean:   Optional[float] = None
    replica:    Optional[int]   = None
    status:     str = "UNPROCESSED"
    auto_label: Optional[str]   = None   # generated by build_auto_labels()


# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

def duration_str(start: Optional[datetime], end: Optional[datetime]) -> str:
    """Return elapsed time as HH:MM:SS string."""
    if start is None or end is None:
        return ""
    delta = end - start
    total_s = int(abs(delta.total_seconds()))
    h, rem = divmod(total_s, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def load_ism(path: Path | str) -> IsmRecord:
    """
    Load a single .ism file and return an IsmRecord.

    Parameters
    ----------
    path : Path or string pointing to the .ism file

    Returns
    -------
    IsmRecord with freq [Hz], Z_re [Ohm], Z_im [Ohm] and metadata.

    Notes
    -----
    - Z_im is returned positive in the capacitive region
      (EIS convention: Z = Z_re - j*Z_im).
      Zahner returns Z_im with negative sign -> sign is flipped here.
    - The internal ISM temperature (T_ism_str) is corrupted (~-0.2 C)
      and must never be used for temperature assignment.
    """
    path = Path(path)
    f = IsmImport(str(path))

    freq   = np.array(f.getFrequencyArray())
    Z_cmpl = np.array(f.getComplexImpedanceArray())
    Z_re   = Z_cmpl.real
    Z_im   = -Z_cmpl.imag   # flip sign: Zahner stores Z_im as negative

    t_start = f.getMeasurementStartDateTime()
    t_end   = f.getMeasurementEndDateTime()

    return IsmRecord(
        path      = path,
        freq      = freq,
        Z_re      = Z_re,
        Z_im      = Z_im,
        t_start   = t_start,
        t_end     = t_end,
        duration  = duration_str(t_start, t_end),
        system    = f.getSystemString() or "",
        T_ism_str = f.getStartTemperatureString() or "",
        n_points  = int(f.getNumberOfSamples()),
    )


def scan_condition_dir(condition_dir: Path | str) -> list[IsmRecord]:
    """
    Scan a condition folder and load all .ism files.

    Parameters
    ----------
    condition_dir : folder such as Raw data/P00_XX_condition/

    Returns
    -------
    List of IsmRecord sorted by t_start (chronological order).
    Files that cannot be opened are skipped with a warning.
    """
    condition_dir = Path(condition_dir)
    ism_files = sorted(condition_dir.glob("*.ism"))

    if not ism_files:
        print(f"  [WARNING] No .ism files found in {condition_dir}")
        return []

    records = []
    for p in ism_files:
        try:
            rec = load_ism(p)
            records.append(rec)
        except Exception as e:
            print(f"  [WARNING] Could not read {p.name}: {e}")

    # Sort chronologically by measurement start time
    records.sort(key=lambda r: r.t_start or datetime.min)
    return records


def records_to_dataframe(records: list[IsmRecord]) -> pd.DataFrame:
    """
    Convert a list of IsmRecord to a DataFrame for display and export.

    Columns
    -------
    file, t_start, t_end, duration, n_points,
    T_nominal, T_mean, T_std, pO2_mean, replica, status
    """
    rows = []
    for r in records:
        rows.append({
            "file":      r.path.name,
            "t_start":   r.t_start.strftime("%H:%M:%S") if r.t_start else "",
            "t_end":     r.t_end.strftime("%H:%M:%S")   if r.t_end   else "",
            "duration":  r.duration,
            "n_points":  r.n_points,
            "T_nominal": r.T_nominal,
            "T_mean":    round(r.T_mean, 2)  if r.T_mean  is not None else None,
            "T_std":     round(r.T_std,  3)  if r.T_std   is not None else None,
            "pO2_mean":  r.pO2_mean,
            "replica":   r.replica,
            "status":    r.status,
        })
    return pd.DataFrame(rows)


def extract_T_from_filename(filename: str) -> Optional[int]:
    """
    Extract nominal temperature from an already-labeled filename.

    Examples
    --------
    'sample_400C.ism'   -> 400
    'sample_400C_1.ism' -> 400
    Returns None if the pattern is not found (sequential / unlabeled file).
    """
    m = re.search(r"_(\d{2,4})[Cc](?:_\d+)?\.ism$", filename, re.IGNORECASE)
    if m:
        return int(m.group(1))
    return None


def extract_replica_from_filename(filename: str) -> Optional[int]:
    """
    Extract the replica number from an already-labeled filename.

    The convention used by this pipeline (and by the user's manual labeling):
        _{T}C.ism       -> replica 1  (first measurement — no numeric suffix)
        _{T}C_1.ism     -> replica 2
        _{T}C_2.ism     -> replica 3
        _{T}C_{k-1}.ism -> replica k

    Examples
    --------
    'sample_400C.ism'   -> 1
    'sample_400C_1.ism' -> 2
    'sample_400C_9.ism' -> 10
    Returns None for sequential / unlabeled files.
    """
    # Has suffix: _NNNc_K.ism  -> replica = K + 1
    m = re.search(r"_\d{2,4}[Cc]_(\d+)\.ism$", filename, re.IGNORECASE)
    if m:
        return int(m.group(1)) + 1
    # No suffix: _NNNc.ism -> replica = 1
    m = re.search(r"_\d{2,4}[Cc]\.ism$", filename, re.IGNORECASE)
    if m:
        return 1
    return None
