"""
pipeline/ingest.py
==================
Load EIS .ism files acquired with Zahner software and extract their data and metadata.

Most important functions
-------------------------
load_ism(path)           -> Load a single .ism file and return an IsmRecord with freq, Z_re, Z_im and metadata.
scan_condition_dir(dir)  -> list of IsmRecord for an entire condition folder
duration_str(start, end) -> elapsed time string HH:MM:SS

Physical units
--------------
freq  : Hz
Z_re  : Ohm  (real part of impedance)
Z_im  : Ohm  (imaginary part of impedance, positive in the capacitive region)
datetime: Python datetime, timezone-aware if present in the ISM file

Python libraries and EIS convention use Z = Z_re - j*Z_im,
where Z_im is positive in the capacitive region. 
Zahner returns Z_im with negative sign -> sign is flipped in load_ism().

"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from zahner_analysis.file_import.ism_import import IsmImport


# ---------------------------------------------------------------------------
# Data class
# ---------------------------------------------------------------------------

@dataclass
class IsmRecord:
    """
    Holds all data for a single .ism file.

    Attributes
    ----------
    path       : absolute Path to the file
    freq       : frequency array [Hz], descending order as output by Zahner
    Z_re       : real part of impedance [Ohm]
    Z_im       : imaginary part [Ohm], positive in the capacitive region
    t_start    : measurement start datetime
    t_end      : measurement end datetime
    duration   : elapsed time string HH:MM:SS
    system     : instrument identifier string (e.g. 'Zennium Pro')
    T_ism_str  : internal ISM temperature string: CORRUPTED (~-0.2 C), do NOT use for temperature assignment; this field is stored for documentation only
    n_points   : number of frequency points

    Fields populated by Stage 1 (furnace log matching)
    ---------------------------------------------------
    T_nominal  : nominal temperature [C], rounded to nearest multiple of 25
    T_mean     : mean furnace temperature during measurement [C]
    T_std      : std of furnace temperature during measurement [C]
    pO2_mean   : mean pO2 during each ism measurement [bar], computed as (max+min)/2
    replica    : replica index within the (T_nominal) group, 1-based
    status     : VALID | UNSTABLE | OUTSIDE_RANGE | OUT_OF_RANGE
    """
    path:      Path
    freq:      np.ndarray
    Z_re:      np.ndarray
    Z_im:      np.ndarray
    t_start:   Optional[datetime] = None
    t_end:     Optional[datetime] = None
    duration:  str = ""
    system:    str = ""
    T_ism_str: str = ""    # corrupted field; stored for documentation only
    n_points:  int = 0

    # Populated by Stage 1
    T_nominal:  Optional[float] = None
    T_mean:     Optional[float] = None
    T_std:      Optional[float] = None
    pO2_mean:   Optional[float] = None
    replica:    Optional[int]   = None
    status:     str = "UNPROCESSED"
    auto_label: Optional[str]   = None   # generated by build_auto_labels()


# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

def duration_str(start: Optional[datetime], end: Optional[datetime]) -> str:
    """
    Return elapsed time as HH:MM:SS string.

    Examples
    --------
    >>> duration_str(datetime(2026, 1, 1, 10, 0, 0), datetime(2026, 1, 1, 11, 30, 5))
    '01:30:05'
    >>> duration_str(None, None)
    ''
    """
    if start is None or end is None:
        return ""
    delta = end - start
    total_s = int(abs(delta.total_seconds()))
    h, rem = divmod(total_s, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def load_ism(path: Path | str) -> IsmRecord:
    """
    Load a single .ism file and return an IsmRecord.

    Parameters
    ----------
    path : Path or string pointing to the .ism file

    Returns
    -------
    IsmRecord with freq [Hz], Z_re [Ohm], Z_im [Ohm] and metadata.

    Notes
    -----
    - Z_im is returned positive in the capacitive region
      (EIS convention: Z = Z_re - j*Z_im).
      Zahner returns Z_im with negative sign -> sign is flipped here.
    - The internal ISM temperature (T_ism_str) is corrupted (~-0.2 C)
      and must never be used for temperature assignment.

    Examples
    --------
    >>> rec = load_ism("Raw data/cond/sample_400C.ism")  # doctest: +SKIP
    >>> rec.n_points == len(rec.freq)  # doctest: +SKIP
    True
    """
    path = Path(path)
    f = IsmImport(str(path))

    freq   = np.array(f.getFrequencyArray())
    Z_cmpl = np.array(f.getComplexImpedanceArray())
    Z_re   = Z_cmpl.real
    Z_im   = -Z_cmpl.imag   # flip sign: Zahner stores Z_im as negative

    t_start = f.getMeasurementStartDateTime()
    t_end   = f.getMeasurementEndDateTime()

    return IsmRecord(
        path      = path,
        freq      = freq,
        Z_re      = Z_re,
        Z_im      = Z_im,
        t_start   = t_start,
        t_end     = t_end,
        duration  = duration_str(t_start, t_end),
        system    = f.getSystemString() or "",
        T_ism_str = f.getStartTemperatureString() or "",
        n_points  = int(f.getNumberOfSamples()),
    )


def scan_condition_dir(condition_dir: Path | str) -> list[IsmRecord]:
    """
    Scan a condition folder and load all .ism files.

    Parameters
    ----------
    condition_dir : folder such as Raw data/P00_XX_condition/

    Returns
    -------
    List of IsmRecord sorted by t_start (chronological order).
    Files that cannot be opened are skipped with a warning.

    Examples
    --------
    >>> records = scan_condition_dir("Raw data/P00_XX_condition")  # doctest: +SKIP
    >>> [r.path.name for r in records]  # doctest: +SKIP
    ['sample_400C.ism', 'sample_425C.ism']
    """
    condition_dir = Path(condition_dir)
    ism_files = sorted(condition_dir.glob("*.ism"))

    if not ism_files:
        print(f"  [WARNING] No .ism files found in {condition_dir}")
        return []

    records = []
    failed  = 0
    for p in ism_files:
        try:
            rec = load_ism(p)
            records.append(rec)
        except Exception as e:
            print(f"  [WARNING] Could not read {p.name}: {e}")
            failed += 1

    if failed:
        print(f"  [WARNING] {failed}/{len(ism_files)} file(s) failed to load in {condition_dir.name}")
    if not records:
        print(f"  [WARNING] No records loaded from {condition_dir.name} "
              f"(all {len(ism_files)} file(s) failed - check file integrity or format)")

    # Sort chronologically by measurement start time
    records.sort(key=lambda r: r.t_start or datetime.min)
    return records


def records_to_dataframe(records: list[IsmRecord]) -> pd.DataFrame:
    """
    Convert a list of IsmRecord to a DataFrame for display and export.

    Columns
    -------
    file, t_start, t_end, duration, n_points,
    T_nominal, T_mean, T_std, pO2_mean, replica, status

    Examples
    --------
    >>> from pathlib import Path
    >>> r = IsmRecord(path=Path("s_400C.ism"), freq=np.array([1.0]),
    ...               Z_re=np.array([1.0]), Z_im=np.array([1.0]), n_points=1)
    >>> df = records_to_dataframe([r])
    >>> df.loc[0, "file"], int(df.loc[0, "n_points"]), df.loc[0, "status"]
    ('s_400C.ism', 1, 'UNPROCESSED')
    """
    rows = []
    for r in records:
        rows.append({
            "file":      r.path.name,
            "t_start":   r.t_start.strftime("%H:%M:%S") if r.t_start else "",
            "t_end":     r.t_end.strftime("%H:%M:%S")   if r.t_end   else "",
            "duration":  r.duration,
            "n_points":  r.n_points,
            "T_nominal": r.T_nominal,
            "T_mean":    round(r.T_mean, 2)  if r.T_mean  is not None else None,
            "T_std":     round(r.T_std,  3)  if r.T_std   is not None else None,
            "pO2_mean":  r.pO2_mean,
            "replica":   r.replica,
            "status":    r.status,
        })
    return pd.DataFrame(rows)


def extract_T_from_filename(filename: str) -> Optional[int]:
    """
    Extract nominal temperature from an already-labeled filename.

    Returns None if the pattern is not found (sequential / unlabeled file).

    Examples
    --------
    >>> extract_T_from_filename('sample_400C.ism')
    400
    >>> extract_T_from_filename('sample_400C_1.ism')
    400
    >>> extract_T_from_filename('sample_seq_01.ism') is None
    True
    """
    m = re.search(r"_(\d{2,4})[Cc](?:_\d+)?\.ism$", filename, re.IGNORECASE)
    if m:
        return int(m.group(1))
    return None


def extract_replica_from_filename(filename: str) -> Optional[int]:
    """
    Extract the replica number from an already-labeled filename.

    The convention used by this pipeline (and by the user's manual labeling):
        _{T}C.ism       -> replica 1  (first measurement; no numeric suffix)
        _{T}C_1.ism     -> replica 2
        _{T}C_2.ism     -> replica 3
        _{T}C_{k-1}.ism -> replica k

    Returns None for sequential / unlabeled files.

    Examples
    --------
    >>> extract_replica_from_filename('sample_400C.ism')
    1
    >>> extract_replica_from_filename('sample_400C_9.ism')
    10
    >>> extract_replica_from_filename('sample_seq_01.ism') is None
    True
    """
    # Has suffix: _NNNc_K.ism  -> replica = K + 1
    m = re.search(r"_\d{2,4}[Cc]_(\d+)\.ism$", filename, re.IGNORECASE)
    if m:
        return int(m.group(1)) + 1
    # No suffix: _NNNc.ism -> replica = 1
    m = re.search(r"_\d{2,4}[Cc]\.ism$", filename, re.IGNORECASE)
    if m:
        return 1
    return None


# ---------------------------------------------------------------------------
# CSV / TXT entry point (for non-Zahner instruments)
# ---------------------------------------------------------------------------

def load_csv_spectrum(path: Path | str) -> IsmRecord:
    """
    Load a single EIS spectrum from a CSV or TXT file.

    The file must have a header line with these exact column names:
        freq, Z_re, Z_im                    (minimum)
        freq, Z_re, Z_im, temperature       (with temperature)
        freq, Z_re, Z_im, temperature, pO2  (with pO2, enables Brouwer/stage 5)

    Separator can be comma, semicolon, or tab.
    Z_im must be positive in the capacitive region (standard EIS convention).

    Parameters
    ----------
    path : path to .csv or .txt file

    Returns
    -------
    IsmRecord with freq, Z_re, Z_im populated.
    T_nominal is set from the filename if the _NNNc pattern is present.
    T_mean is set to the mean of the temperature column if present.
    pO2_mean is set to the mean of the pO2 column if present (bar), else None.

    Examples
    --------
    >>> import tempfile, os
    >>> tmp = tempfile.NamedTemporaryFile("w", suffix="_400C.csv", delete=False)
    >>> _ = tmp.write("freq,Z_re,Z_im\\n1000,10.0,5.0\\n")
    >>> tmp.close()
    >>> rec = load_csv_spectrum(tmp.name)
    >>> rec.n_points, rec.T_nominal, rec.replica
    (1, 400.0, 1)
    >>> os.unlink(tmp.name)
    """
    path = Path(path)
    raw  = path.read_text(encoding="utf-8", errors="replace")

    # detect separator from the header line
    _lines = raw.splitlines()
    if not _lines or not raw.strip():
        raise ValueError(f"{path.name}: file is empty")
    header_line = _lines[0]
    if "\t" in header_line:
        sep = "\t"
    elif ";" in header_line:
        sep = ";"
    else:
        sep = ","

    df = pd.read_csv(path, sep=sep, engine="python")
    df.columns = [c.strip() for c in df.columns]

    required = {"freq", "Z_re", "Z_im"}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(
            f"{path.name}: missing column(s) {missing}. "
            f"Header must contain exactly: freq, Z_re, Z_im "
            f"(and optionally temperature). Found: {list(df.columns)}"
        )

    freq = df["freq"].to_numpy(dtype=float)
    Z_re = df["Z_re"].to_numpy(dtype=float)
    Z_im = df["Z_im"].to_numpy(dtype=float)

    # Sign-convention guard: the pipeline stores Z_im positive in the
    # capacitive region, while most third-party exports (Gamry, EC-Lab,
    # ZView) write the physical negative sign. Without this check such a
    # file loads fine and then strip_inductive() silently discards nearly
    # every point as "inductive".
    finite = Z_im[np.isfinite(Z_im)]
    if finite.size and (finite < 0).mean() > 0.5:
        raise ValueError(
            f"{path.name}: {int((finite < 0).sum())}/{finite.size} points have "
            f"Z_im < 0. This pipeline expects Z_im positive in the capacitive "
            f"region; the file likely uses the physical sign convention "
            f"(Gamry/EC-Lab/ZView default). Flip the Z_im column sign and retry."
        )

    # mean() over a column with NaNs returns NaN, which would pass the
    # "is not None" checks downstream and poison the temperature filters
    T_mean = float(df["temperature"].mean()) if "temperature" in df.columns else None
    if T_mean is not None and math.isnan(T_mean):
        T_mean = None
    # same NaN guard as temperature: a NaN pO2 must read as "absent", not as a
    # value that survives the downstream "notna" checks and skips the Brouwer gate
    pO2_mean = float(df["pO2"].mean()) if "pO2" in df.columns else None
    if pO2_mean is not None and math.isnan(pO2_mean):
        pO2_mean = None
    T_nom  = _extract_T_csv_only(path.name)

    rec           = IsmRecord(path=path, freq=freq, Z_re=Z_re, Z_im=Z_im,
                               n_points=len(freq))
    rec.T_nominal = float(T_nom) if T_nom is not None else None
    rec.T_mean    = T_mean
    rec.pO2_mean  = pO2_mean
    rec.replica   = _extract_replica_csv(path.name)
    return rec


def _extract_replica_csv(filename: str) -> int:
    """Return replica index from CSV/TXT filename (_NNNc_K -> K+1, _NNNc -> 1)."""
    m = re.search(r"_\d{2,4}[Cc]_(\d+)\.(csv|txt)$", filename, re.IGNORECASE)
    if m:
        return int(m.group(1)) + 1
    return 1


def scan_input_spectra(sample_dir: Path | str) -> Optional[pd.DataFrame]:
    """
    Scan {sample_dir}/input_spectra/ and build a DataFrame compatible with
    the VALID sheet produced by stage1_labeling.

    Returns None if the input_spectra folder does not exist (normal Zahner workflow).

    Each subfolder of input_spectra/ is treated as one condition.
    Files must follow the naming convention anyname_NNNc.csv (or .txt).
    Files without a recognisable temperature in the name are skipped with a warning.

    Columns returned
    ----------------
    file, full_path, condition, T_nominal, T_mean, pO2_mean, replica

    Examples
    --------
    >>> df = scan_input_spectra("EIS program/SampleID")  # doctest: +SKIP
    >>> df[["file", "condition", "T_nominal"]].head(1)  # doctest: +SKIP
                file      condition  T_nominal
    0  sample_400C.csv  Ar_600_400_25      400.0
    """
    sample_dir   = Path(sample_dir)
    spectra_root = sample_dir / "input_spectra"

    if not spectra_root.exists():
        return None

    rows     = []
    n_skip   = 0

    loose_files = [
        f for f in spectra_root.iterdir()
        if f.is_file() and f.suffix.lower() in {".csv", ".txt"}
        and not f.name.startswith(".")
    ]
    if loose_files:
        print(
            f"  [WARNING] {len(loose_files)} file(s) found directly in input_spectra/ "
            f"and will be ignored. Place files inside a condition sub-folder: "
            f"input_spectra/{{Gas_SCCM_Gas_SCCM_Tmax_Tmin_deltaT}}/{{file}}.csv"
        )

    for cond_dir in sorted(spectra_root.iterdir()):
        if not cond_dir.is_dir():
            continue
        condition = cond_dir.name
        files = sorted(
            f for f in cond_dir.iterdir()
            if f.suffix.lower() in {".csv", ".txt"} and not f.name.startswith(".")
        )
        if not files:
            continue

        for f in files:
            T_nom = extract_T_from_filename(f.name)
            if T_nom is None:
                T_nom = _extract_T_csv_only(f.name)
            if T_nom is None:
                print(f"  [SKIP] {f.name}: no temperature found in filename "
                      f"(expected pattern: _NNNc before the extension)")
                n_skip += 1
                continue

            try:
                rec = load_csv_spectrum(f)
            except Exception as e:
                print(f"  [SKIP] {f.name}: {e}")
                n_skip += 1
                continue

            rows.append({
                "file":      f.name,
                "full_path": str(f),
                "condition": condition,
                "T_nominal": float(T_nom),
                "T_mean":    rec.T_mean,
                "pO2_mean":  rec.pO2_mean,
                "replica":   rec.replica,
            })

    if not rows:
        print("[input_spectra] No valid files found.")
        return pd.DataFrame()

    df = pd.DataFrame(rows)

    n_cond = df["condition"].nunique()
    n_files = len(df)
    n_T     = df["T_nominal"].nunique()
    print(f"input_spectra: {n_cond} condition(s), {n_files} file(s), "
          f"{n_T} unique temperature(s)")
    if n_skip:
        print(f"  {n_skip} file(s) skipped (see warnings above)")
    has_T = df["T_mean"].notna().any()
    print(f"  temperature column present: {has_T} "
          f"({'Arrhenius available' if has_T else 'Arrhenius will be skipped'})")
    has_pO2 = df["pO2_mean"].notna().any()
    print(f"  pO2 column present: {has_pO2} "
          f"({'Brouwer available' if has_pO2 else 'Brouwer will be skipped'})")

    return df


def _extract_T_csv_only(filename: str) -> Optional[int]:
    """Match _NNNc pattern in CSV/TXT filenames."""
    m = re.search(r"_(\d{2,4})[Cc](?:_\d+)?\.(csv|txt)$", filename, re.IGNORECASE)
    if m:
        return int(m.group(1))
    return None
